CREATE TABLE CATCH (
    ID INT PRIMARY KEY,
    FISH VARCHAR(255),
    WEIGHT INT,
    LENGTH INT,
    LOCATION VARCHAR(255)
);

INSERT INTO CATCH (ID, FISH, WEIGHT, LENGTH, LOCATION) VALUES (1, 'Salmon', 10, 5, 'Uljua');